# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea721b5d66616afa8eb8c502397a7c2521a136932deda004510fa4dc401800b152ef1b93167d8e71ced6522d9f31c6771cdecf3d584abbcf3aa82096a1946764

test:
  secret_key_base: 97e6fc9b5b6c0078697debce64a412d696362d074f1c8206e56fa50cd9574622b48b6dcb1bbe7c30066fe7f5226dc2bf2c937b1307407e74f3714931bf5117aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
